spring:
  application:
    name: blogspot-services
  datasource:
    url: jdbc:h2:mem:db_blogspot
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    locations: "classpath:db/migration"
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8282

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h in millisecond
    expiration-time: 3600000